# Generated by Django 6.0.7 on 2026-08-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_like'),
        ('core', '0005_make_image_url_nullable'),
    ]

    operations = [
    ]
